---
- name: P1
  hosts: all
  gather_facts: false
  tasks:
    - name: T1
      cisco.ios.ios_command:
        commands: 
          - show ip interface brief
      register: out

    - name: T2
      ansible.builtin.debug:
        msg:
          - '{{ out.changed }}'
          - '{{ out.failed }}'
          - '{{ out.stdout }}'
          - '{{ out.stdout_lines }}'
