---
- name: P1
  hosts: all
  gather_facts: false
  tasks:
    - name: T1
      cisco.ios.ios_command:
        commands:
          - show run int g{{ item }}
      loop: '{{ range(1, 5) }}'
      register: out

    - name: T2
      ansible.builtin.debug:
        var: out
